# Site settings
title: Software Loom
email: software-loom@proton.me
description: Software research, design and development services.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://software-loom.gr" 

twitter_username:
github_username:

# Build settings
markdown: kramdown
